site_name: Dark Insider Role-play Community
site_description: Dark Insider Role-play Community Documentation
site_author: mujina7569

extra_css:
  - stylesheets/extra.css

site_url: https://dark-insider.vercel.app

plugins:
  # - social:
  #     cards_layout_dir: layouts
  #     cards_layout: custom
  #     debug: true
  - search
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - git-authors
  - blog:
      enabled: true
      blog_dir: blog
      post_dir: "{blog}/articles"
      post_url_format: "{categories}/{slug}"
      post_readtime: true
      categories: true
      authors: true
      authors_profiles: true

theme:
  # favicon: images/favicon.png
  name: material
  logo: 
  font:
    text: Krub
    code: Roboto Mono
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    # - navigation.footer
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
  custom_dir: overrides
markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 'Dark Insider': 'index.md'
  - 'กฏการอยู่ร่วมกัน': 'rules.md'
  - 'เนื้อเรื่อง': 'lore\story.md'
  - 'เริ่มเล่น': 
    - 'howto\roles.md' # แนวทางการเล่น
  - 'จุนซุย':
    - 'เกี่ยวกับจุนซุย': 'junsui.md'
    - 'ไมนด์': 'mind.md'
    - 'คลาสต่างๆ': 'classes.md'
    - 'เขตการควบคุม': 'departments.md'
    - 'ระบบเลื่อนขั้นจุนซุย': 'ranks.md'
  - 'อินไซด์เดอร์':
    - 'เกี่ยวกับอินไซด์เดอร์': 'insider.md'
    - 'การปราบอินไซด์เดอร์': 'resurrection.md'
    - 'ระดับขั้นอินไซด์เดอร์': 'classifications.md'
  - 'การสร้างตัวละคร': 
    # - 'การส่งตัวละคร': ''
    # - 'ตัวละครจุนซุย': ''
    # - 'ตัวละครอินไซด์เดอร์': ''
    # - 'ระบบสเตตัส': 'stats.md'
    - 'ระบบสกิล': 'skills.md'
  - 'ระบบต่างๆ ภายในคอมมู':
    - 'ระบบภารกิจ':
      - 'ระบบภารกิจ': 'mission.md'
      # - 'Assignment Mission': 'mission.md'
      # - 'Player Mission': 'mission.md'
      # - 'ระบบ Freeze': 'mission.md'
    - 'ระบบไอเทม และร้านค้า': 'items.md'
    # - 'ระบบต่อสู้': 'index.md'
    - 'ระบบสนับสนุนอื่นๆ': 'systems.md'
  # - 'แฟ้มข้อมูลพิเศษ':
      # - 'แฟ้มข้อมูลที่เปิดเผยได้ #1: Insider': 'mission.md'
      # - 'แฟ้มข้อมูลที่เปิดเผยได้ #2: องค์กรจุนซุย': 'mission.md'
      # - 'คุจากุ และโคโจ': 'mission.md'
      # - 'คุโมะ': 'mission.md'
      # - 'NPC': 'mission.md'
      # - 'บันทึกลับของหน่วยข่าวกรอง': 'mission.md'
  - 'blank': 'blank.md'
  - 'test': 'test.md'
  - Blog:
    - blog/index.md
    # - blog/authors.md

extra:
  generator: false
  # social: 
  # - icon: fontawesome/brands/discord
  #   link: #

  status:
    # <identifier>: <description>
    # <identifier>: <description>

  analytics:
    provider: google
    property: !ENV ANALYTICS_KEY
    feedback:
      title: หน้านี้ให้ข้อมูลที่ต้องการรึเปล่า?
      ratings:
        - icon: material/emoticon-happy-outline
          name: เยี่ยมเลย
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: ไม่มีข้อมูลที่ต้องการ
          data: 0
          note: >- 
            สามารถแจ้งข้อมูลไม่ครบ หรือขาดได้ที่ Discord: mujina7569

copyright:
  2024 Dark Insider 
