authors:
  system:
    name: System        # Author name
    description: no data # Author description
    avatar: docs\imgs\Logo\thumbnail_03.jpg         # Author avatar
    slug: system           # Author profile slug
    # url: url            # Author website URL